# Generated by Django 3.1.7 on 2021-05-25 02:50

import Quizzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='Description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Image',
            field=models.ImageField(default=1, upload_to=Quizzer.models.upload_Quiz_Image, verbose_name='Quiz Image'),
            preserve_default=False,
        ),
    ]
