# Generated by Django 3.1.7 on 2021-05-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0003_quiz_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Description',
            field=models.TextField(),
        ),
    ]
