# Generated by Django 3.1.7 on 2021-05-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzer', '0005_choice_choicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Picks',
            field=models.IntegerField(default=0),
        ),
    ]
